### ISSUE TITLE
就算离职都无法消除你内心深处的吐槽吗？

### ISSUE THREAD

**Issue by gch116620** [gch116620/blog#3]
吐槽：我们公司真是。。。我实在没法吐槽了，家族式产业，一个个的什么都不懂，让程序员干人力，让销售干会计，就为了省招人的钱，两面三刀，说话不算数，工资拖欠，等等等等。

就当是报复吧，也为了下一个继承我职位的人能看到，我做了个小东西，希望它能明白我的苦心，也希望他不要沉陷在这个***的公司里。

1、新建一个js文档，我用的工具是Hbuilder，并写入以下代码：
（复制粘贴即可，没必要看完）
`
console.log("如果你会点英文的话，仔细看看。下面的不是乱码")
console.log("warning! this isn't useless! don't delete it and try to comply with the procedure below!")
console.log("if you can understand encoder for html developing,try to translate the phrase below by the tools,trust me,it will save the whole career for you.")
console.log("%E4%B8%8D%E8%A6%81%E7%9B%B8%E4%BF%A1%E8%A2%AB%E6%89%BF%E8%AF%BA%E7%9A%84%E5%B9%B4%E7%BB%88%E5%A5%96%EF%BC%8C%E6%A0%B9%E6%9C%AC%E6%B2%A1%E6%9C%89%EF%BC%81")
console.log("%E4%B8%8D%E8%A6%81%E7%9B%B8%E4%BF%A1%E8%A2%AB%E6%89%BF%E8%AF%BA%E7%9A%84%E7%94%B5%E8%84%91%E5%8D%87%E7%BA%A7%EF%BC%8C%E6%A0%B9%E6%9C%AC%E6%B2%A1%E6%9C%89%EF%BC%81")
console.log("%E4%B8%8D%E8%A6%81%E7%9B%B8%E4%BF%A1%E8%A2%AB%E6%89%BF%E8%AF%BA%E7%9A%84%E5%8D%87%E8%81%8C%EF%BC%8C%E6%A0%B9%E6%9C%AC%E4%B8%8D%E5%8F%AF%E8%83%BD%EF%BC%81")
console.log("%E4%B8%80%E5%88%87%E9%AB%98%E5%B1%82%E8%81%8C%E4%BD%8D%E5%85%A8%E9%83%BD%E6%98%AF%E8%80%81%E6%9D%BF%E7%9A%84%E4%BA%B2%E6%88%9A%E5%92%8C%E6%9C%8B%E5%8F%8B%EF%BC%8C%E6%B0%B8%E8%BF%9C%E4%B8%8D%E4%BC%9A%E6%98%AF%E4%BD%A0%E3%80%82")
console.log("%E4%BB%96%E4%BC%9A%E4%B8%8D%E6%96%AD%E7%BB%99%E4%BD%A0%E5%AE%89%E6%8E%92%E9%9D%9E%E4%BD%A0%E8%81%8C%E4%BD%8D%E7%9A%84%E5%B7%A5%E4%BD%9C%EF%BC%8C%E5%8C%85%E6%8B%AC%E4%BD%86%E4%B8%8D%E9%99%90%E4%BA%8E%E8%80%83%E8%AF%95%EF%BC%8C%E4%BA%BA%E5%8A%9B%20%E8%A1%8C%E6%94%BF%EF%BC%8C%E7%94%9A%E8%87%B3%E9%94%80%E5%94%AE%EF%BC%8C%E7%BE%8E%E5%85%B6%E5%90%8D%E6%9B%B0%E7%BB%99%E4%BD%A0%E9%94%BB%E7%82%BC%E3%80%82")
console.log("%E4%B8%8D%E8%A6%81%E7%9B%B8%E4%BF%A1%E4%BB%BB%E4%BD%95%E7%9A%84%E9%A1%B9%E7%9B%AE%E5%A5%96%E9%87%91%EF%BC%8C%E8%B5%9A%E4%BA%86%E4%B8%80%E7%99%BE%E4%B8%87%E8%BF%9E1000%E5%9D%97%E9%83%BD%E4%B8%8D%E4%BC%9A%E5%88%86%E7%BB%99%E4%BD%A0%E3%80%82")
console.log("%E4%B8%8D%E8%A6%81%E7%9B%B8%E4%BF%A1%E6%B6%A8%E5%B7%A5%E8%B5%84%EF%BC%8C%E6%9C%80%E5%A4%9A%E5%BC%A0500%E3%80%82")
console.log("%E7%9B%B8%E4%BF%A1%E6%88%91%EF%BC%8C%E4%BB%96%E4%BB%AC%E7%9C%9F%E7%9A%84%E4%BB%80%E4%B9%88%E4%B9%9F%E4%B8%8D%E6%87%82%EF%BC%8C%E6%97%A0%E8%AE%BA%E6%98%AF%E5%B8%82%E5%9C%BA%20%20%E8%BF%98%E6%98%AF%E4%BA%A7%E5%93%81%E8%BF%90%E8%90%A5%20%E7%94%9A%E8%87%B3%E4%BA%A7%E5%93%81%E5%BC%80%E5%8F%91%E3%80%82")
console.log("%E5%A6%82%E6%9E%9C%E5%8F%AF%E4%BB%A5%EF%BC%8C%E8%B5%B6%E5%BF%AB%E7%A6%BB%E5%BC%80%E8%BF%99%E9%87%8C%E3%80%82")
console.log("Tool's URL is http://tool.oschina.net/encode?type=4")`

懂web的人一眼就看出这是啥，没错这就是传说中的URL转码，不知道的请自行百度。

2、我们新建一个html文件，照样是Hbuilder,在<!Doctype HTML>前加入空行，两三万行即可，保证别人不会一眼看到你的代码。如图：
![image](https://cloud.githubusercontent.com/assets/22024045/22961942/a780ce94-f384-11e6-9a0f-8644589c3d45.png)

3、写一个藏头诗，避免让那些你讨厌的人看出端倪，我写的如下（包括html代码）
![image](https://cloud.githubusercontent.com/assets/22024045/22961950/b916e904-f384-11e6-88da-0129534221e1.png)

然后在最下方，引入你刚才做的js文件，引入方法为
`<script src="c:\windows\1.js" type="text/javascript" charset="utf-8"></script>`
请大家看看每一行的开头，连起来就是“请看看console.log”

console.log是何物？是web开发中常见的调试日志

保存网页之后，打开这个网页，我们只看到了你写的藏头诗，如图
![image](https://cloud.githubusercontent.com/assets/22024045/22961970/eafc3b72-f384-11e6-8045-6b2e2cad4b5b.png)

4、打开调试日志
我们按F12打开调试工具，然后点击上面的 console选项卡，就会出现下图：
![image](https://cloud.githubusercontent.com/assets/22024045/22962119/e4e3e59a-f385-11e6-8463-d9145333c1cc.png)

5、看最后
有一个网址，我们点击打开
![image](https://cloud.githubusercontent.com/assets/22024045/22962110/da8b1dc0-f385-11e6-9f1a-3ce76c7bba9f.png)

是一个转码个工具，好，我们把console.log里面的内容复制进去，然后点击 URL解码，之后如图

![image](https://cloud.githubusercontent.com/assets/22024045/22962100/ce673eac-f385-11e6-80f6-fb290d3a8bad.png)

看看左边，翻译出了什么？
好吧，不用谢我。这也没什么技术含量。
我不是坏人，这只是我对压抑了两年工作的控诉，对家族式（村落式）企业的厌恶！

还有，这个东西，放到IE主页就可以了~总会被看到的

**Comment by xyazh515** [comment]
66666

**Comment by HakimC** [comment]
surprise_ motherfucker
